base_url = "https://travisbrown.dev"

title = "travisbrown.dev"
compile_sass = true
build_search_index = true
generate_feed = true

theme = "slim"

taxonomies = [
  {name = "tags", rss = true}
]

[markdown]
highlight_code = true

[extra]
slim_summary = false
slim_content = true
slim_footer = "Copyright © 2023 <a href='https://travisbrown.dev'>Travis Brown</a>"

slim_social = [
    {url = "https://bsky.app/profile/travisbrown.dev", name = "Bluesky"},
    {url = "https://mastodon.social/@travisbrown", name = "Mastodon"},
    {url = "https://github.com/travisbrown", name = "GitHub"},
    {url = "https://stackoverflow.com/users/334519/travis-brown", name = "Stack Overflow"}
]
